name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  # Allow manual triggering of the workflow
  workflow_dispatch:
  schedule:
    - cron: '12 14 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use appropriate version and cache dependencies)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      # Step 3: Install project dependencies (if any)
      - name: Install dependencies
        run: |
          git clone https://github.com/valetzx/flow-wx
          cp -r flow-wx/* .
          npm install


      # Step 4: Build the project (prepare static files in dist/)
      - name: Build static files
        env:
          API_DOMAINS: ${{ secrets.API_DOMAINS }}
          IMG_DOMAINS: ${{ secrets.IMG_DOMAINS }}
          IMG_CACHE: ${{ secrets.IMG_CACHE }}
        run: |
          npm run build
          cd dist/api
          rm -rf wx
          wget ${API_DOMAINS}api/wx
      # Step 5: Deploy the dist/ folder to the 'pages' branch for GitHub Pages
      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ASS_TOKEN }}
          publish_dir: dist
          publish_branch: pages
